metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.110, mac: '1c:83:41:30:be:11', disk: nvme0n1, network_interface: enp3s0}
    workers:
      hosts
        metal1: {ansible_host: 192.168.1.111, mac: '1c:83:41:30:8e:d4', disk: nvme0n1, network_interface: enp3s0}

